import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from './UI/header'
import { Footer } from './UI/footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {



  return (
    <html lang="en">
      <script async src="node_modules/@material-tailwind/html/scripts/ripple.js"></script>
      <body className={inter.className}>
 
        <div style={{display: 'grid', gridTemplateRows: 'auto 1fr auto', height: '100vh'}}>
        <Header/>
        <div className="h-full w-full">
        {children}
        </div>
        <Footer/>
        </div>
    
        </body>
    </html>
  )
}
